#!/bin/bash
# regenerates dotfiles from .gen files.
haddiff=0
for src in *.gen; do
  base=${src%.gen}
  dst=$HOME/.$base
  if ! test -f $dst; then
    echo generating $base
    ./$src >$dst
    continue
  fi
  if cmp -s $dst <(./$src); then
    continue
  fi
  haddiff=1
  diff -u --label=live/.$base --label=head/.$base $dst <(./$src)
  if test "$regen" = 1; then
    echo "applied the above diff."
    ./$src >$dst
  fi
done
if test "$haddiff" = 1 -a "$regen" != 1; then
  echo 'use "regen=1 make" to apply the diffs.'
fi
