#!/bin/bash

test "$HOSTNAME" = ipi && xsetroot -solid '#ffffff'
xsetroot -cursor_name arrow
xset r rate 300 40
xset s off
xset -dpms
xset +fp ~/.fonts
xmodmap ~/.xmodmap
synclient MaxTapTime=0

exec i3
