#!/bin/bash

xsetroot -cursor_name left_ptr
xset r rate 300 40
xset s 1200
xset dpms 1200 1200 1200

setxkbmap ushu -variant ushu
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

rm -rf /home/rlblaster/contestapplet.conf.bak

cd /home/rlblaster/.xmonad
./sysstat &
./gmail.sh &
cd

terminal &
exec xmonad
