#!/bin/bash

xsetroot -cursor_name left_ptr
xset r rate 300 40
xset s 1200
xset dpms 1200 1200 1200

xmodmap ~/.xmodmap

rm -rf /home/rlblaster/contestapplet.conf.bak

cd /home/rlblaster/.xmonad
./sysstat &
./gmail.sh &
cd

urxvt -name urxvt-start-on-1 &
firefox &
exec xmonad
