#!/bin/bash

xsetroot -cursor_name left_ptr
xset r rate 300 40
xset s 1200
xset dpms 1200 1200 1200

xmodmap ~/.xmodmap

autocutsel -fork
autocutsel -selection PRIMARY -fork

rm -rf /home/rlblaster/contestapplet.conf.bak

cd /home/rlblaster/.xmonad
./sysstat &
./gmail.sh &
cd

xterm -name XM-start-on-1 &
firefox &
exec xmonad
