#!/bin/bash

if test $# -ne 1; then
	echo "Usage: $0 [1..4]"
	echo ""
	echo "Waits until super + F[1..4] isn't pressed"
	exit 0
fi

while ! test -e "/dev/shm/wmfn$1"; do
	sleep 0.2
done

rm "/dev/shm/wmfn$1"
