#!/bin/bash

set -e

# Check for flashcards and any reminders before checking email.
flashcard
firstrem="$(head -c 10 ~/rems)"
curdate="$(date +%Y-%m-%d)"
if test "$curdate" '<' "$firstrem"; then
  /usr/bin/mutt "$@"
else
  echo "Please take care of the reminders first in ~/rems."
fi;
