#!/bin/bash

# Add something like this
# ACTION=="add", SUBSYSTEM=="input", ENV{ID_INPUT_KEYBOARD}=="?*", NAME="daskeyboard", RUN+="/home/rlblaster/.bin/postswitch"
# to /etc/udev/rules.d/99-local.rules

cd $(dirname $0)/..
nohup >/dev/null 2>/dev/null bash -c '
sleep 1
home=$(pwd)
export DISPLAY=:0
export XAUTHORITY=$home/.Xauthority
xset s 1200
xset r rate 300 40
xmodmap $home/.xmodmap
' &
