#!/bin/bash
# reset x settings to reasonable defaults.
if "$HOSTNAME" = ipi; then
  xsetroot -solid '#ffffff'
else
  xsetroot -solid '#000'
  hsetroot -solid 0
  nohup compton --backend glx --vsync opengl-swc >/dev/null 2>/dev/null &
fi
xsetroot -cursor_name arrow
xset r rate 300 40
xset s off
xset -dpms
xset +fp ~/.fonts
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap
