#!/bin/bash
# reset x settings to reasonable defaults.
if test "$HOSTNAME" = ipi; then
  xsetroot -solid '#ffffff'
else
  xsetroot -solid '#000'
fi
xsetroot -cursor_name arrow
xset r rate 300 40
xset s off
xset -dpms
xset +fp ~/.fonts
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap
