#!/bin/bash
if test "$#" -ne 1; then
  echo 'usage: ta [hostname]'
  echo 'run tmux attach on a remote host.'
  exit
fi
test "$1" = work && export SSH_AUTH_SOCK=/home/$USER/.cache/agent-tty
ssh -t -X -Y "$1" LANG=en_US.UTF-8 tmux attach
