#!/bin/bash
# checks for any outstanding stuff i have to do:
# - energy subtraction because of the email check,
# - daily flashcards,
# - reminders,
# - todo,
# - unread emails.

set -e
flashcard

# todo
if test -s ~/todo; then
  echo todo:
  if test "$(head -c1 ~/todo)" != "#"; then
    echo "  invalid todo file."
  fi
  sed -n 's/^#[a-z]/  &/p' ~/todo
  echo
fi

# reminders
curdate="$(date +%Y-%m-%d)"
awk -v curdate=$curdate '
  $1 <= curdate {
    if (init == "") {
      print "reminders:"
      init = 1
    }
    print "  " $0
  }
  END {
    if (init) print ""
  }' ~/.rems

# check for email.
printsubjects='
  function printheader() {
    if (initialized == "") {
      initialized = 1
      print email ":"
    }
  }
  /^\* [0-9]+ FETCH/ {
    seen = $0 ~ /\\Seen/
  }
  match($0, /^Subject: (.*)$/, ary) {
    printheader()
    printf "  %s", (seen ? " " : "u") " " ary[1]
    subjectmode = 1
    next
  }
  subjectmode == 1 {
    printf "%s", $0
  }
  /^$/ {
    if (subjectmode) {
      subjectmode = 0
      print ""
    }
  }
  END {
    if (initialized == 1) {
      print ""
    }
  }
'
echo -n "checking email..."
(echo -en '\r\e[K'; while read user pass inbox; do
  nl=$'\n'
  cmd="a0 login $user $pass$nl"
  cmd+="a1 select $inbox$nl"
  cmd+="a2 fetch 1:99 (flags body.peek[header.fields (subject)])$nl"
  cmd+="a3 logout$nl"
  ncat='ncat --no-shutdown --crlf --ssl-verify imap.gmail.com 993'
  $ncat <<<"$cmd" | tr -d '\r' | awk -v email=$user "$printsubjects" | de2047 &
done <~/.config/.myemails; wait) | sponge
