#!/bin/bash
# checks for any outstanding stuff i have to do:
# - daily flashcards,
# - reminders,
# - todo,
# - unread emails.

set -e
flashcard

# todo
if test -s ~/todo; then
  echo todo:
  sed 's/^/  /' ~/todo
  echo
fi

# reminders
curdate="$(date +%Y-%m-%d)"
awk -v curdate=$curdate '
  $1 <= curdate {
    if (init == "") {
      print "reminders:"
      init = 1
    }
    print "  " $0
  }
  END {
    if (init) print ""
  }' ~/.rems

# check for email.
printsubjects='
  function printheader() {
    if (initialized == "") {
      initialized = 1
      print email ":"
    }
  }
  /^\* [0-9]+ FETCH/ {
    seen = $0 ~ /\\Seen/
  }
  match($0, /^Subject: (.*)$/, ary) {
    printheader()
    print "  " (seen ? " " : "u") " " ary[1]
  }
  END {
    if (initialized == 1) {
      print ""
    }
  }
'
cat ~/.config/.myemails | while read user pass inbox; do
  echo -en "checking $user..."
  nl=$'\n'
  cmd="a0 login $user $pass$nl"
  cmd+="a1 select $inbox$nl"
  cmd+="a2 fetch 1:99 (flags body.peek[header.fields (subject)])$nl"
  cmd+="a3 logout$nl"
  r="$(ncat --no-shutdown --crlf --ssl-verify imap.gmail.com 993 <<<"$cmd")"
  echo -en "\r\e[K"
  awk -v email=$user "$printsubjects" <<<"$r"
done
