#!/bin/bash
# Starts chrome with no autocompletion in its omnibox.
google-chrome \
  --enable-features="OmniboxUIExperimentMaxAutocompleteMatches<Trial" \
  --force-fieldtrials="Trial/Group" \
  --force-fieldtrial-params="Trial.Group:UIMaxAutocompleteMatches/1/UIMaxAutocompleteMatchesByProvider/*%3A0"
